<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-VanitasStudios_WebApp-4a8e1271-df2d-48a7-851c-397ee61581a6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\img\background.png" />
    <Content Remove="wwwroot\img\favicon\VS_favicon.ico" />
    <Content Remove="wwwroot\img\Horus.png" />
    <Content Remove="wwwroot\img\Logo.png" />
    <Content Remove="wwwroot\img\mask-monolith.png" />
    <Content Remove="wwwroot\img\StatueVS.png" />
    <Content Remove="wwwroot\img\VanitasLogo.png" />
    <Content Remove="wwwroot\img\VanitasStudio_NOBG.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.26.0" />
    <PackageReference Include="LigerShark.WebOptimizer.Core" Version="3.0.477" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.*" />
    <PackageReference Include="WebMarkupMin.AspNetCore6" Version="2.21.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="wwwroot\img\favicon\VS_favicon.ico" />
    <Resource Include="wwwroot\img\Horus.png" />
    <Resource Include="wwwroot\img\Logo.png" />
    <Resource Include="wwwroot\img\mask-monolith.png" />
    <Resource Include="wwwroot\img\VanitasLogo.png" />
    <Resource Include="wwwroot\img\VanitasStudio_NOBG.png" />
  </ItemGroup>

</Project>
