// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VanitasStudios_WebApp.Data;

#nullable disable

namespace VanitasStudios_WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226131026_InitialIdentityAndSchema")]
    partial class InitialIdentityAndSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("ContentOrdId")
                        .HasColumnType("int")
                        .HasColumnName("Content_Ord_ID");

                    b.Property<int>("TagOrdId")
                        .HasColumnType("int")
                        .HasColumnName("Tag_Ord_ID");

                    b.HasKey("ContentOrdId", "TagOrdId")
                        .HasName("PK__Order__16EB5FFAF718821E");

                    b.HasIndex("TagOrdId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Comment", b =>
                {
                    b.Property<int>("IdComm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Comm");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComm"));

                    b.Property<int?>("AnswerId")
                        .HasColumnType("int")
                        .HasColumnName("Answer_ID");

                    b.Property<string>("CommText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Comm_Text");

                    b.Property<int>("CommentUserId")
                        .HasColumnType("int")
                        .HasColumnName("Comment_User_ID");

                    b.Property<int>("ContentId")
                        .HasColumnType("int")
                        .HasColumnName("Content_ID");

                    b.Property<DateTime>("DataPub")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("Data_Pub")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("IdComm")
                        .HasName("PK__Comment__560C251E2B77EB82");

                    b.HasIndex("AnswerId");

                    b.HasIndex("CommentUserId");

                    b.HasIndex("ContentId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Content", b =>
                {
                    b.Property<int>("IdC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_C");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdC"));

                    b.Property<DateTime?>("DataEdit")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("Data_Edit");

                    b.Property<DateTime>("DataPub")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("Data_Pub")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DescC")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Desc_C");

                    b.Property<int>("EditorId")
                        .HasColumnType("int")
                        .HasColumnName("Editor_ID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TypeC")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("articolo")
                        .HasColumnName("Type_C");

                    b.HasKey("IdC")
                        .HasName("PK__Content__B87EA50961BA4A46");

                    b.HasIndex("EditorId");

                    b.ToTable("Content", (string)null);
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Evaluate", b =>
                {
                    b.Property<int>("UserLikeId")
                        .HasColumnType("int")
                        .HasColumnName("User_Like_ID");

                    b.Property<int>("CommLikeId")
                        .HasColumnType("int")
                        .HasColumnName("Comm_Like_ID");

                    b.Property<bool>("IsLike")
                        .HasColumnType("bit")
                        .HasColumnName("isLike");

                    b.HasKey("UserLikeId", "CommLikeId")
                        .HasName("PK__Evaluate__1F28091D4ECADA78");

                    b.HasIndex("CommLikeId");

                    b.ToTable("Evaluate", (string)null);
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Image", b =>
                {
                    b.Property<int>("IdI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_I");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdI"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Image_Url");

                    b.Property<bool>("IsThumbnail")
                        .HasColumnType("bit")
                        .HasColumnName("Is_Thumbnail");

                    b.Property<int>("SectionImageId")
                        .HasColumnType("int")
                        .HasColumnName("Section_Image_ID");

                    b.HasKey("IdI")
                        .HasName("PK__Image__B87EA503141B6819");

                    b.HasIndex("SectionImageId");

                    b.ToTable("Image", (string)null);
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Promotion", b =>
                {
                    b.Property<int>("IdPromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Promotion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPromotion"));

                    b.Property<int>("AdminPromoterId")
                        .HasColumnType("int")
                        .HasColumnName("Admin_Promoter_ID");

                    b.Property<DateTime>("DataPromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Promotion")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PromotedId")
                        .HasColumnType("int")
                        .HasColumnName("Promoted_ID");

                    b.HasKey("IdPromotion")
                        .HasName("PK__Promotio__ECECECBEA1BEC634");

                    b.HasIndex("AdminPromoterId");

                    b.HasIndex("PromotedId");

                    b.ToTable("Promotion", (string)null);
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Section", b =>
                {
                    b.Property<int>("IdS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_S");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdS"));

                    b.Property<int>("ContentSId")
                        .HasColumnType("int")
                        .HasColumnName("Content_S_ID");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int")
                        .HasColumnName("Order_num");

                    b.Property<string>("SectionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Section_Text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("IdS")
                        .HasName("PK__Section__B87EA5193321E3F5");

                    b.HasIndex("ContentSId");

                    b.ToTable("Section", (string)null);
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Tag", b =>
                {
                    b.Property<int>("IdT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_T");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdT"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Tag_Name");

                    b.Property<string>("TypeT")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("articolo")
                        .HasColumnName("Type_T");

                    b.HasKey("IdT")
                        .HasName("PK__Tag__B87EA51889DF0D54");

                    b.ToTable("Tag", (string)null);
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Video", b =>
                {
                    b.Property<int>("IdV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_V");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdV"));

                    b.Property<int>("ImageVideoId")
                        .HasColumnType("int")
                        .HasColumnName("Image_Video_ID");

                    b.Property<int>("SectionVideoId")
                        .HasColumnType("int")
                        .HasColumnName("Section_Video_ID");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Video_Url");

                    b.HasKey("IdV")
                        .HasName("PK__Video__B87EA516CAC63B2A");

                    b.HasIndex("SectionVideoId");

                    b.HasIndex(new[] { "ImageVideoId" }, "UQ__Video__57417FA3F6E793E4")
                        .IsUnique();

                    b.ToTable("Video", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VanitasStudios_WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.Content", null)
                        .WithMany()
                        .HasForeignKey("ContentOrdId")
                        .IsRequired()
                        .HasConstraintName("FK_Content_Ord_ID");

                    b.HasOne("VanitasStudios_WebApp.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagOrdId")
                        .IsRequired()
                        .HasConstraintName("FK_Tag_Ord_ID");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Comment", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.Comment", "Answer")
                        .WithMany("InverseAnswer")
                        .HasForeignKey("AnswerId")
                        .HasConstraintName("FK_Answer_ID");

                    b.HasOne("VanitasStudios_WebApp.Models.ApplicationUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("CommentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Comment_User_ID");

                    b.HasOne("VanitasStudios_WebApp.Models.Content", "Content")
                        .WithMany("Comments")
                        .HasForeignKey("ContentId")
                        .IsRequired()
                        .HasConstraintName("FK_Content_ID");

                    b.Navigation("Answer");

                    b.Navigation("Content");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Content", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.ApplicationUser", "Editor")
                        .WithMany("Contents")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Editor");

                    b.Navigation("Editor");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Evaluate", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.Comment", "CommLike")
                        .WithMany("Evaluates")
                        .HasForeignKey("CommLikeId")
                        .IsRequired()
                        .HasConstraintName("FK_Comm_Like_ID");

                    b.HasOne("VanitasStudios_WebApp.Models.ApplicationUser", "UserLike")
                        .WithMany("Evaluates")
                        .HasForeignKey("UserLikeId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Like_ID");

                    b.Navigation("CommLike");

                    b.Navigation("UserLike");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Image", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.Section", "SectionImage")
                        .WithMany("Images")
                        .HasForeignKey("SectionImageId")
                        .IsRequired()
                        .HasConstraintName("FK_Section_Image_ID");

                    b.Navigation("SectionImage");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Promotion", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.ApplicationUser", "AdminPromoter")
                        .WithMany()
                        .HasForeignKey("AdminPromoterId")
                        .IsRequired()
                        .HasConstraintName("FK_Admin_Promoter_ID");

                    b.HasOne("VanitasStudios_WebApp.Models.ApplicationUser", "Promoted")
                        .WithMany()
                        .HasForeignKey("PromotedId")
                        .IsRequired()
                        .HasConstraintName("FK_Promoted_ID");

                    b.Navigation("AdminPromoter");

                    b.Navigation("Promoted");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Section", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.Content", "ContentS")
                        .WithMany("Sections")
                        .HasForeignKey("ContentSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Content_S_ID");

                    b.Navigation("ContentS");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Video", b =>
                {
                    b.HasOne("VanitasStudios_WebApp.Models.Image", "ImageVideo")
                        .WithOne("Video")
                        .HasForeignKey("VanitasStudios_WebApp.Models.Video", "ImageVideoId")
                        .IsRequired()
                        .HasConstraintName("FK_Image_Video_ID");

                    b.HasOne("VanitasStudios_WebApp.Models.Section", "SectionVideo")
                        .WithMany("Videos")
                        .HasForeignKey("SectionVideoId")
                        .IsRequired()
                        .HasConstraintName("FK_Section_Video_ID");

                    b.Navigation("ImageVideo");

                    b.Navigation("SectionVideo");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.ApplicationUser", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Contents");

                    b.Navigation("Evaluates");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Comment", b =>
                {
                    b.Navigation("Evaluates");

                    b.Navigation("InverseAnswer");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Content", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Image", b =>
                {
                    b.Navigation("Video");
                });

            modelBuilder.Entity("VanitasStudios_WebApp.Models.Section", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
